quarkus.application.name="dnd-session-manager"

quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:root}
quarkus.datasource.password=${DB_PASS:root}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:db}:5432/${DB_NAME:dnd}

quarkus.live-reload.instrumentation=true

quarkus.hibernate-orm.database.generation=update

mp.jwt.verify.issuer=https://securetoken.google.com/dnd-manager-auth
smallrye.jwt.verify.key.location=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
quarkus.smallrye-jwt.enabled=true

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-max-age=24H
